import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { BlogProvider } from "./context/BlogContext";
import AuthProvider from "@/components/AuthProvider";
import { AdminBlogProvider } from "./context/admin/AdminBlogContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminBlogProvider>
          <AuthProvider>
            <Navbar />
            <BlogProvider>
              {children}
            </BlogProvider>
            <Footer />
          </AuthProvider>
        </AdminBlogProvider>
      </body>
    </html>
  );
}
